# Generated by Django 4.2.26 on 2025-12-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_work_id', models.CharField(blank=True, help_text="Work reference ID from farmer's system", max_length=100, null=True)),
                ('mukkadam_id', models.IntegerField(help_text='Mukkadam ID from external service')),
                ('transport_provider_id', models.IntegerField(help_text='Transport Provider ID from external service')),
                ('mukkadam_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
