# Generated by Django 4.2.26 on 2025-12-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_allocation_completed_at_allocation_farmer_work_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportProvider',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='transport_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final transport price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='allocated_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Area already allocated', max_digits=10),
        ),
    ]
