# Generated by Django 4.2.26 on 2025-12-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_allocation_crew_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobactivity',
            options={'ordering': ['scheduled_datetime']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='notes',
            new_name='activity_notes',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='farmer_work_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='farmer_contact',
        ),
        migrations.RemoveField(
            model_name='job',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='jobactivity',
            name='estimated_workers_needed',
        ),
        migrations.RemoveField(
            model_name='jobactivity',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='job',
            name='booking_advance_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='booking_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='booking_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='farmer_id',
            field=models.CharField(default=1, help_text='External farmer ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='plot_id',
            field=models.CharField(default=1, help_text='External plot ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_date',
            field=models.DateTimeField(default='2025-10-12', help_text='Scheduled date from API'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total_activities_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='activity_id',
            field=models.CharField(default=1, help_text='External activity ID (e.g., ACT001)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='activity_name',
            field=models.CharField(default='cut', help_text="Activity name from API (e.g., 'Soil Testing', 'Pruning', etc.)", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='estimated_workers',
            field=models.IntegerField(default=10, help_text='Estimated workers needed'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='remaining_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='scheduled_datetime',
            field=models.DateTimeField(default='2025-10-12', help_text='Scheduled date/time for this activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Total from API', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=132, help_text='Base price from API', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocated_area',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Area allocated to this mukkadam', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='job_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='data.jobactivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='own_transport_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='transport_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='transport_provider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='work_date',
            field=models.DateField(default='2025-10-12', help_text='Date when mukkadam will do the work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(help_text='External farm visit ID (e.g., FV123)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Normalized activity type for matching', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='allocated_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='rate_per_acre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='total_area',
            field=models.DecimalField(decimal_places=2, help_text='Total acres for this activity', max_digits=10),
        ),
    ]
