# Generated by Django 4.2.26 on 2026-02-11 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mukkadamactivityrate',
            name='productivity_per_worker',
            field=models.DecimalField(decimal_places=3, default=0.15, help_text='Acres per worker per day (e.g., 0.15 means each worker can do 0.15 acres/day)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
