# Generated by Django 4.2.26 on 2026-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_activitylogtender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukkadam',
            name='mukkadam_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
