# Generated by Django 4.2.26 on 2026-02-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_mukkadam_mukkadam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_type', models.CharField(choices=[('mukkadam', 'Mukkadam Leave'), ('general', 'General Holiday')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mukkadam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='tender.mukkadam')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'leave_type', 'mukkadam')},
            },
        ),
    ]
