# Generated by Django 4.2.26 on 2026-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='crew_on_leave',
            field=models.PositiveIntegerField(default=0, help_text="Number of workers from this mukkadam's crew on leave"),
        ),
    ]
