# Generated by Django 4.2.26 on 2026-02-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_leave_crew_on_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workers', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('mukkadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.mukkadam')),
            ],
        ),
    ]
