# Generated by Django 4.2.26 on 2026-02-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_extraworker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extraworker',
            unique_together={('mukkadam', 'date')},
        ),
    ]
