# Generated by Django 4.2.26 on 2026-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0009_cluster_allocation_cluster_farmer_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='is_strict',
            field=models.BooleanField(default=False),
        ),
    ]
