# Generated by Django 4.2.26 on 2026-02-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0010_jobactivity_is_strict'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='taluka_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='village_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
