# Generated by Django 4.2.26 on 2026-02-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_cluster_district_code_cluster_state_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='village',
        ),
        migrations.RemoveField(
            model_name='job',
            name='plot_id',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='tender.cluster'),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_code', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='tender.cluster')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='tender.farmer')),
            ],
            options={
                'db_table': 'plots',
                'unique_together': {('farmer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActivityScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_days', models.PositiveIntegerField(default=3)),
                ('phase_order', models.PositiveIntegerField(default=0)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_schedule', to='tender.activitycatalog')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='tender.plot'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tender.plot'),
        ),
        migrations.CreateModel(
            name='ClusterActivityScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_days', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_schedule_overrides', to='tender.activitycatalog')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_schedule_overrides', to='tender.cluster')),
            ],
            options={
                'unique_together': {('cluster', 'activity')},
            },
        ),
    ]
