# Generated by Django 4.2.26 on 2026-02-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_remove_farmer_district_remove_farmer_taluka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycatalog',
            name='default_gap_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
