# Generated by Django 4.2.26 on 2026-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_activitycatalog_default_gap_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
