# Generated by Django 4.2.26 on 2026-02-13 06:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_job_booking_amount_job_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='crop_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ClusterActivityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_acre', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_rates', to='tender.activitycatalog')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rates', to='tender.cluster')),
            ],
            options={
                'db_table': 'cluster_activity_rates',
                'unique_together': {('cluster', 'activity')},
            },
        ),
    ]
