# Generated by Django 4.2.26 on 2026-02-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0015_job_crop_name_clusteractivityrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
