# Generated by Django 4.2.26 on 2026-02-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0016_job_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='activity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='booking_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
