# Generated by Django 4.2.26 on 2026-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0017_job_completed_date_alter_job_activity_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='booking_amount',
        ),
        migrations.AlterField(
            model_name='job',
            name='activity_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='booking_type',
            field=models.CharField(default='Tender', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
