# Generated by Django 4.2.26 on 2026-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0018_remove_job_booking_amount_alter_job_activity_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
