# Generated by Django 4.2.26 on 2026-02-14 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0019_job_booking_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mukkadamactivityrate',
            name='mukkadam_ac_mukkada_a41f05_idx',
        ),
        migrations.RemoveField(
            model_name='mukkadamactivityrate',
            name='source',
        ),
        migrations.AlterField(
            model_name='mukkadamactivityrate',
            name='productivity_per_worker',
            field=models.DecimalField(decimal_places=3, default=0.15, help_text='Acres per worker per day', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='mukkadamactivityrate',
            index=models.Index(fields=['mukkadam', 'is_active'], name='mukkadam_ac_mukkada_9ee31f_idx'),
        ),
    ]
