# Generated by Django 4.2.26 on 2026-02-14 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0020_remove_mukkadamactivityrate_mukkadam_ac_mukkada_a41f05_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMukkadamActivityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_acre', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('productivity_per_worker', models.DecimalField(decimal_places=3, default=0.15, help_text='Default efficiency (acres per worker per day)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_mukkadam_defaults', to='tender.activitycatalog')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mukkadam_activity_defaults', to='tender.cluster')),
            ],
            options={
                'db_table': 'cluster_mukkadam_activity_rates',
                'indexes': [models.Index(fields=['cluster', 'activity'], name='cluster_muk_cluster_85e18f_idx')],
                'unique_together': {('cluster', 'activity')},
            },
        ),
    ]
