# Generated by Django 4.2.26 on 2025-12-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_allocations', models.IntegerField(default=0)),
                ('total_area_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_mukkadam_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transport_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocations_by_user', models.JSONField(default=dict, help_text='User-wise allocation count')),
            ],
            options={
                'verbose_name_plural': 'Allocation Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('farmer_name', models.CharField(max_length=255)),
                ('farmer_contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_allocated', 'Partially Allocated'), ('fully_allocated', 'Fully Allocated'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('base_location', models.CharField(max_length=255)),
                ('max_distance', models.IntegerField(help_text='Maximum distance in km')),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['-allocated_at']},
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='completed_at',
            new_name='allocated_at',
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='created_by',
            new_name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='farmer_work_id',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='transport_price',
        ),
        migrations.AddField(
            model_name='allocation',
            name='allocated_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Area allocated to this mukkadam', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='own_transport_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price if using own transport', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='allocated', max_length=20),
        ),
        migrations.AddField(
            model_name='allocation',
            name='transport_type',
            field=models.CharField(choices=[('provider', 'Transport Provider'), ('own', 'Own Transport'), ('none', 'No Transport Needed')], default='provider', max_length=20),
        ),
        migrations.AddField(
            model_name='allocation',
            name='work_date',
            field=models.DateField(blank=True, help_text='Date when mukkadam will do the work', null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='transport_provider_id',
            field=models.IntegerField(blank=True, help_text='Transport Provider ID (if using provider)', null=True),
        ),
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('pruning', 'Pruning'), ('april_pruning', 'April Pruning'), ('pasting', 'Pasting'), ('first_fail_fut_removal', 'First Fail Fut Removal'), ('second_fail_fut_removal', 'Second Fail Fut Removal'), ('bagal_bali_fut_removal', 'Bagal Bali Fut Removal'), ('first_dipping', 'First Dipping'), ('second_dipping', 'Second Dipping'), ('third_dipping', 'Third Dipping'), ('bunch_thinning', 'Bunch Thinning'), ('finger_thinning', 'Finger Thinning'), ('berry_thinning', 'Berry Thinning'), ('shoot_tying', 'Shoot Tying'), ('bunch_selection', 'Bunch Selection'), ('bunch_tying', 'Bunch Tying'), ('shenda_topping', 'Shenda Topping'), ('paper_wrapping', 'Paper Wrapping'), ('paper_removal', 'Paper Removal'), ('harvesting', 'Harvesting'), ('new_plantation', 'New Plantation')], max_length=50)),
                ('location', models.CharField(help_text='Plot location', max_length=255)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in acres', max_digits=10)),
                ('allocated_area', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Area already allocated', max_digits=10, null=True)),
                ('scheduled_date', models.DateField(help_text='When this activity should be done')),
                ('estimated_workers_needed', models.IntegerField(help_text='Estimated number of workers')),
                ('rate_per_acre', models.DecimalField(decimal_places=2, help_text='Rate per acre for this activity', max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='data.job')),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='job_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='data.jobactivity'),
        ),
    ]
