# Generated by Django 4.2.26 on 2025-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_allocationstats_job_transportprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocation',
            name='farmer_work_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='transport_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final transport price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocated_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area allocated to this mukkadam', max_digits=10, null=True),
        ),
    ]
