# Generated by Django 4.2.26 on 2025-12-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delete_transportprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='crew_size',
            field=models.IntegerField(blank=True, help_text='Number of workers for this specific allocation', null=True),
        ),
    ]
