# Generated by Django 4.2.26 on 2025-12-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_job_options_alter_jobactivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobactivity',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobactivity',
            name='remaining_area',
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='job_id',
            field=models.CharField(db_index=True, default=1, help_text='External job ID (e.g., FV123, WORK-001)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='transport_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_name',
            field=models.CharField(help_text="Activity name from API (e.g., 'Pruning', 'Harvesting')", max_length=255),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Normalized activity type', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['mukkadam_id'], name='data_alloca_mukkada_72d652_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['work_date'], name='data_alloca_work_da_439dce_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['allocated_at'], name='data_alloca_allocat_30529e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobactivity',
            index=models.Index(fields=['job_id', 'activity_id'], name='data_jobact_job_id_64817e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobactivity',
            index=models.Index(fields=['job_id'], name='data_jobact_job_id_d159c9_idx'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
