# Generated by Django 4.2.26 on 2025-12-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_job_options_alter_jobactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_name',
            field=models.CharField(help_text='Activity name from API', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Normalized activity type', max_length=100, null=True),
        ),
    ]
