
"""
Django settings for crop project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# settings.py
# ============================================
# CORS & CSRF CONFIGURATION
# ============================================

# CORS Settings (at the top, after imports)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # React dev server
    "http://localhost:5173",      # Vite dev server  
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8001",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "https://supply.bharatintelligence.ai",
    "https://demand.bharatintelligence.ai",
    "https://payment.bharatintelligence.ai",
    "https://ops.bharatintelligence.ai",
    "https://allocation.bharatintelligence.ai",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:8001",
]

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # True only in production with HTTPS
SESSION_COOKIE_SECURE = False  # True only in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8001",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Set to True only in production with HTTPS
session_COOKIE_SECURE = False # Set to True only in production with HTTPS
from decouple import config, Csv

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l6c$=vdsv7n-ng7cd_^6fvi7lig^+_a2!dzg5oy1^a6qklw$9t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Add this for Render
CORS_ALLOW_ALL_ORIGINS = True
# 5. DRF Config

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'data',
    
    'storages',
    'rest_framework',
    'rest_framework.authtoken',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # ✅ Add this for development
    ],
}

# Presign API Configuration
PRESIGN_API_URL = 'https://demand.bharatintelligence.ai/chat/presign_obj_api/'
PRESIGN_API_TOKEN = 'Token c432208626a204d2d8de3d00b29f948eae61ebdb'  # ✅ Replace with real token


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'allocate.urls'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ✅ ADD THIS: Configure templates to find React's index.html
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
		f"{BASE_DIR}/allocate/static",
	],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'allocate.wsgi.application'
# settings.py

# ===== GEMINI API KEYS (Add 5 keys) =====
# Get free keys from: https://aistudio.google.com/apikey

GEMINI_API_KEY_1 = os.environ.get('GEMINI_API_KEY_1', 'AIzaSyCh0DeWCZr8m3kF4LDB2A_xoAlqbmKjvgs')
GEMINI_API_KEY_2 = os.environ.get('GEMINI_API_KEY_2', 'AIzaSyDGCAaYBIoySFkgom_KHm6wtk2m12wVLBw')
# Backward compatibility
GEMINI_API_KEY = GEMINI_API_KEY_1

# ==============================================
# AWS S3 SETTINGS (PRESIGNED URL MODE)
# ==============================================

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='ap-south-1')


# --- 2. ENABLE SIGNING ---
AWS_QUERYSTRING_AUTH = True  # <--- This generates the '?Signature=...'
AWS_QUERYSTRING_EXPIRE = 3600  # Link expires in 1 hour (adjust as needed)
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_URL_PROTOCOL = 'https:'

# --- 3. SECURITY ---
AWS_DEFAULT_ACL = None  # Use Bucket Owner Enforced (Private)
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# --- 4. STORAGE ENGINE ---
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

#     # Media files
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # use this for normal Postgres
#         'NAME': 'registration_db',
#         'USER': 'postgres',
#         'PASSWORD': 'new_password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#         'OPTIONS': {
#             'client_encoding': 'UTF8',
#         },
#     }
# }

# allocate/settings.py
# SUPPLY_API_URL = 'http://localhost:8000'
# ALLOCATION_API_URL = 'http://localhost:8001'

# allocate/settings.py
SUPPLY_API_URL = 'https://supply.bharatintelligence.ai'
ALLOCATION_API_URL = 'https://allocation.bharatintelligence.ai'
# Tell Celery to use Redis, not RabbitMQ
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'


# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Use your Redis server
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'allocation_app',
        'TIMEOUT': 3600,  # 1 hour default
    }
}



# Cache timeouts (in seconds)
CACHE_MUKKADAM_TIMEOUT = 3600  # 1 hour
CACHE_FARMER_TIMEOUT = 3600    # 1 hour
CACHE_TRANSPORT_TIMEOUT = 21600  # 6 hours
CACHE_JOB_TIMEOUT = 1800  # 30 minutes
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # use this for normal Postgres
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Agrointel45677Kishan',
        'HOST': 'allocation.c12ggig2u4ig.ap-south-1.rds.amazonaws.com',
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}
EXOTEL_TOKEN_URL = "https://call.bharatintelligence.ai/oauth/token"
# EXOTEL_SERVICE_BASE_URL = "https://658fb4b69f28.ngrok-free.app/api/calls"
EXOTEL_CLIENT_ID = "kishan_localhost"
EXOTEL_CLIENT_SECRET= "bi_M-n87nBu4a1QAs6ve7-o4FMrvm9hOMZ5npqVB-lhS-Q",
EXOTEL_SERVICE_BASE_URL = "https://call.bharatintelligence.ai"
EXOTEL_CALLER_ID = "+91-804-7361465"
# DATABASES = {
#      'default': {
#          'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
#         'NAME': config('DB_NAME'),
#          'USER': config('DB_USER'),
#          'PASSWORD': config('DB_PASSWORD'),
#          'HOST': config('DB_HOST'),
#          'PORT': config('DB_PORT', default='5432'),
#          'OPTIONS': {
#              'connect_timeout': 10,
#          }
#      }
# }
# DATABASES = {
#     'default': dj_database_url.config(
#         default='postgresql://postgress:nxJpZNoU4tirJexUiaPFTLvSPjiWwqyT@dpg-d3u7mhbe5dus739f6mjg-a.oregon-postgres.render.com/registerdb_od8n',
#         # default='postgresql://postgress:nxJpZNoU4tirJexUiaPFTLvSPjiWwqyT@dpg-d3u7mhbe5dus739f6mjg-a/registerdb_od8n',
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }
# At the end of settings.py
APPEND_SLASH = False  # Prevent automatic slash redirects


# In settings.py - MUCH SIMPLER!
MUKADAM_WEBHOOK_URLS = {
    'default': 'http://localhost:5000/api/webhooks/job-notification'
}

BASE_URL = 'https://workcrop.onrender.com'



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# ========================================
# CELERY CONFIGURATION
# ========================================
import os



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py - UPDATE THIS



# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']